**DSR-Base Assessment**

*This Project was about analyzing an estimate of the number of people living with HIV in different South African districts collected by Two companies(Survey and Fay-Heriott)*



*   The total Time taken to do project 3Hrs:20min

**Exploratory Data Analysis(EDA)**

In [48]:
# libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re

In [13]:
# Reading data and showing the first five rows
data = pd.read_excel("data/pone.0212445.s004.xlsx", header=1)
data.head(10)

            District  Code     Estimate  ...  NoPLHIV  NoPLHIV_LCL  NoPLHIV_UCL
0       Buffalo City   BUF       Survey  ...   102437        77340       127534
1       Buffalo City   BUF  Fay-Heriott  ...   101693        83092       123691
2  City of Cape Town   CPT       Survey  ...   200751       117517       283985
3  City of Cape Town   CPT  Fay-Heriott  ...   232409       167359       320548
4         West Coast   DC1       Survey  ...    11302            0        22789
5         West Coast   DC1  Fay-Heriott  ...    17114        10107        28639
6             Cacadu  DC10       Survey  ...    34732        15922        53542
7             Cacadu  DC10  Fay-Heriott  ...    40729        28083        58298
8            Amatole  DC12       Survey  ...    98884        65407       132361
9            Amatole  DC12  Fay-Heriott  ...   106783        81721       138230

[10 rows x 9 columns]

In [12]:
# Looking at the last ten in the dataset
data.tail(10)

                     District Code  ... NoPLHIV_LCL  NoPLHIV_UCL
94                  eThekwini  ETH  ...      373303       631317
95                  eThekwini  ETH  ...      408472       616456
96       City of Johannesburg  JHB  ...      369778       660996
97       City of Johannesburg  JHB  ...      406743       645818
98                   Mangaung  MAN  ...       52872       122480
99                   Mangaung  MAN  ...       74646       136792
100  Nelson Mandela Bay Metro  NMA  ...       39923       154995
101  Nelson Mandela Bay Metro  NMA  ...       71964       154757
102           City of Tshwane  TSH  ...      228239       494661
103           City of Tshwane  TSH  ...      255052       450265

[10 rows x 9 columns]

In [9]:
# Statistical Summary
data.describe()

       Prevalence_%  Prevalence_LCL  ...    NoPLHIV_LCL    NoPLHIV_UCL
count    104.000000      104.000000  ...     104.000000     104.000000
mean      12.113805        8.507655  ...   89210.009615  162458.317308
std        4.978586        4.635330  ...   89791.909524  145761.963447
min        1.584032        0.000000  ...       0.000000    3552.000000
25%        8.869829        4.911882  ...   28057.750000   68507.750000
50%       11.750000        8.165653  ...   69407.500000  136812.000000
75%       15.718785       11.617805  ...  115101.250000  181302.250000
max       25.000000       18.218028  ...  408472.000000  660996.000000

[8 rows x 6 columns]

In [10]:
# Dataset Information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 104 entries, 0 to 103
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   District        104 non-null    object
 1   Code            104 non-null    object
 2   Estimate        104 non-null    object
 3   Prevalence_%    104 non-null    float64
 4   Prevalence_LCL  104 non-null    float64
 5   Prevalence_UCL  104 non-null    float64
 6   NoPLHIV         104 non-null    int64
 7   NoPLHIV_LCL     104 non-null    int64
 8   NoPLHIV_UCL     104 non-null    int64
dtypes: float64(3), int64(3), object(3)
memory usage: 7.4+ KB

**Question 2A**

***What is the total number of people living with HIV (NoPLHIV) in the listed districts according to the Survey estimate?***

In [45]:
# Filtering dataset
survey_data = data[data.Estimate.isin(['Survey'])]

# Filtering by relavent columns
total_noplhiv = survey_data[['District', 'Code', 'Estimate', 'NoPLHIV']]

# sorting by NoPLHIV(lowest to highest)
total_noplhiv.sort_values('NoPLHIV')

                      District  Code Estimate  NoPLHIV
84                     Namakwa   DC6   Survey     3317
86              Pixley ka Seme   DC7   Survey     9501
4                   West Coast   DC1   Survey    11302
16                     Xhariep  DC16   Survey    11777
88                     Siyanda   DC8   Survey    13673
44                    Overberg   DC3   Survey    17039
82               Central Karoo   DC5   Survey    17808
76         John Taolo Gaetsewe  DC45   Survey    20323
66                        Eden   DC4   Survey    25191
22              Cape Winelands   DC2   Survey    30706
6                       Cacadu  DC10   Survey    34732
12                   Joe Gqabi  DC14   Survey    37766
24                 Fezile Dabi  DC20   Survey    45550
90               Frances Baard   DC9   Survey    47040
64   Dr Ruth Segomotsi Mompati  DC39   Survey    51450
80                   West Rand  DC48   Survey    60313
54                      Vhembe  DC34   Survey    70373
58                   Waterberg  DC36   Survey    71577
78                  Sekhukhune  DC47   Survey    77489
42                      iLembe  DC29   Survey    78178
34                     Amajuba  DC25   Survey    82210
38                uMkhanyakude  DC27   Survey    86131
98                    Mangaung   MAN   Survey    87676
52                      Mopani  DC33   Survey    87968
32                  uMzinyathi  DC24   Survey    93587
100   Nelson Mandela Bay Metro   NMA   Survey    97459
8                      Amatole  DC12   Survey    98884
72                     Sisonke  DC43   Survey    99572
0                 Buffalo City   BUF   Survey   102437
68           Dr Kenneth Kaunda  DC40   Survey   102584
74                  Alfred Nzo  DC44   Survey   104363
10                  Chris Hani  DC13   Survey   114849
20          Thabo Mofutsanyana  DC19   Survey   115006
56                   Capricorn  DC35   Survey   116351
62         Ngaka Modiri Molema  DC38   Survey   117661
30                    uThukela  DC23   Survey   118124
18               Lejweleputswa  DC18   Survey   123868
48                    Nkangala  DC31   Survey   126270
26                         Ugu  DC21   Survey   142979
14                  O.R. Tambo  DC15   Survey   160352
40                   uThungulu  DC28   Survey   162238
36                    Zululand  DC26   Survey   171411
70                    Sedibeng  DC42   Survey   197713
2            City of Cape Town   CPT   Survey   200751
46                Gert Sibande  DC30   Survey   208067
60           Bojanala Platinum  DC37   Survey   212904
28               uMgungundlovu  DC22   Survey   221073
50                   Ehlanzeni  DC32   Survey   281104
102            City of Tshwane   TSH   Survey   361450
92                  Ekurhuleni   EKU   Survey   462059
94                   eThekwini   ETH   Survey   502310
96        City of Johannesburg   JHB   Survey   515387

**Question 2B**

***What is the average NoPLHIV of the two estimates used for “Xhariep”?***

In [75]:
# Filtering dataset by Xhariep district 
xhariep_df = data[(data.District.isin(['Xhariep']))]

# calling the Relevent columns
xhariep_df = xhariep_df[['District', 'Code', 'Estimate', 'NoPLHIV']]

# Printing the average of Xhariep District
xhariep_df.mean(axis=1)

16    11777.0
17    12718.0
dtype: float64

**QUESTION 2C**

***Add a column and populate it with the number of people not living with HIV for each row.***

In [83]:
# Creating new column showing the number of people no infected
data['NoPNLHIV'] = (data['NoPLHIV'] / (data['Prevalence_%']/ 100))

# Printing the dataset with added column
data.head()

            District Code     Estimate  ...  NoPLHIV_LCL  NoPLHIV_UCL      NoPNLHIV
0       Buffalo City  BUF       Survey  ...        77340       127534  7.532132e+05
1       Buffalo City  BUF  Fay-Heriott  ...        83092       123691  7.532099e+05
2  City of Cape Town  CPT       Survey  ...       117517       283985  3.860596e+06
3  City of Cape Town  CPT  Fay-Heriott  ...       167359       320548  3.860587e+06
4         West Coast  DC1       Survey  ...            0        22789  4.185926e+05

[5 rows x 10 columns]

**QUESTION 2D**

*What is the total NoPLHIV in all the cities (districts with the word “city” or “metro” in the name)?*

**QUESTION 3**


*Write the original data (without the caption - originally row 1) with the extra columns as comma-separated values (CSV) to a new .csv file*